// Mocks generated by Mockito 5.4.6 from annotations
// in notclawdbot/test/service/service_proxy_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:notclawdbot/client/client_forward.dart' as _i3;
import 'package:notclawdbot/dto/source.dart' as _i8;
import 'package:notclawdbot/service/service_pow.dart' as _i7;
import 'package:notclawdbot/service/service_templating.dart' as _i5;
import 'package:shelf/shelf.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClientForward].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientForward extends _i1.Mock implements _i3.ClientForward {
  MockClientForward() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response> forward(_i2.Request? request) =>
      (super.noSuchMethod(
            Invocation.method(#forward, [request]),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(this, Invocation.method(#forward, [request])),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ServiceTemplating].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceTemplating extends _i1.Mock implements _i5.ServiceTemplating {
  MockServiceTemplating() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String render(String? url, String? challenge, int? difficulty) =>
      (super.noSuchMethod(
            Invocation.method(#render, [url, challenge, difficulty]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#render, [url, challenge, difficulty]),
            ),
          )
          as String);
}

/// A class which mocks [ServicePow].
///
/// See the documentation for Mockito's code generation for more information.
class MockServicePow extends _i1.Mock implements _i7.ServicePow {
  MockServicePow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get difficulty =>
      (super.noSuchMethod(Invocation.getter(#difficulty), returnValue: 0)
          as int);

  @override
  String computeChallenge(_i8.Source? source, DateTime? expiration) =>
      (super.noSuchMethod(
            Invocation.method(#computeChallenge, [source, expiration]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#computeChallenge, [source, expiration]),
            ),
          )
          as String);

  @override
  bool verifyPow({required String? challenge, required String? nonce}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPow, [], {
              #challenge: challenge,
              #nonce: nonce,
            }),
            returnValue: false,
          )
          as bool);
}
